project_id = "fuwtowsfoxarzklbydnq"

[functions.fetch-youtube-info]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.check-flights]
verify_jwt = false

[functions.flights-api]
verify_jwt = false
